dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

sudo: false

install:
  - pip install numpy pandas torch codecov pytest pytest-cov
  - pip install -e .

script:
  - pytest --cov=./

after_success:
  - codecov
